name: sample

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  demo:
    runs-on: macos-latest
    name: Sample demo
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update iOS version Info.plist
        uses: damienaicheh/update-ios-version-info-plist-action@v1.2.0
        with:
          info-plist-path: './samples/Info.plist'
          bundle-short-version-string: '2.0'
          bundle-version: '2'
          print-file: true
